blog/index/views.py
from flask import Blueprint, render_template

index = Blueprint("index", __name__, url_prefix="/", static_folder="../static")


@index.route("/")
def main_page():
    return render_template(
        "base.html"
    )

blog/report/views.py
from flask import Blueprint, render_template

report = Blueprint('report', __name__, url_prefix='/reports', static_folder='../static')


@report.route('/')
def report_list():
    return render_template(
        'reports/report_list.html'
    )

blog/user/views.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user, login_user
from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash

from blog.extensions import db
from blog.forms.user import UserRegisterForm
from blog.models import User

user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@user.route('/register/', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user.user_get', pk=current_user.id))

    form = UserRegisterForm(request.form)
    errors = []

    if request.method == 'POST' and form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append('Email already exists')
            return render_template('users/user_register.html', form=form)

        _user = User(
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            password=generate_password_hash(form.password.data),
        )

        db.session.add(_user)
        db.session.commit()

        login_user(_user)

    return render_template(
        'users/user_register.html',
        form=form,
        errors=errors,
    )


@user.route('/')
@login_required
def user_list():
    users = User.query.all()
    return render_template(
        'users/user_list.html',
        users=users,
    )


@user.route('/<int:pk>')
@user.route('/<int:pk>/')
@login_required
def user_get(pk: int):
    from blog.models import User
    selected_user = User.query.filter_by(id=pk).one_or_none()

    if selected_user is None:
        raise NotFound(f"User id:{pk}, not found")

    return render_template(
        'users/user_detail.html',
        user=selected_user,
    )


# def get_user_name(pk: int):
#     if pk in USERS:
#         user_name = USERS[pk]["name"]
#     else:
#         raise NotFound("User id:{}, not found".format(pk))
#     return user_name

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}My blog - {% endblock %}</title>

      {% block css %}
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
      {% endblock %}
  </head>
  <body>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

    {% include 'navbar.html' %}

    <div class="container">
        {% block body %}{% endblock %}
    </div>

    {% block js %}
        <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    {% endblock %}
  </body>
</html>

blog/templates/hello.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hello from flask</title>
</head>
<body>
    {% if name %}
        <h1>Hello {{ name }}!</h1>
    {% else %}
        <h1>Hello, World!</h1>
    {% endif %}
</body>
</html>

blog/templates/index.html
{% extends 'base.html' %}


{% block title %}
    Index Page
{% endblock %}


{% block body %}
    <h1>Hello index page!</h1>
{% endblock %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<!--    navbar-expand-lg bg-body-tertiary-->
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('index.main_page') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.user_list') }}">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('author.author_list') }}">Authors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('article.list') }}">Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('report.report_list') }}">Reports</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('admin.index') }}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout ({{ current_user.email }})</a>
        </li>
        {% endif %}

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>